# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "blackntight"
license = "MIT"
licenselink = "http://htdvisser.mit-license.org/"
description = "blackntight is GovanifY's new website theme based on base16"
homepage = "https://govanify.com"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.14

[author]
  name = "GovanifY"
  homepage = "https://govanify.com"
